AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WhatsappFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin/whatsapp
      Handler: main
      Runtime: go1.x
      Timeout: 30
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role"
      Environment:
        Variables:
          ENVIRONMENT: production
      Events:
        MyEvent:
          Type: Api
          Properties:
            Path: /whatsapp
            Method: post
            
  EmailFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: ./bin/email
    Handler: main
    Runtime: go1.x
    Timeout: 30
    Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role"
    Environment:
      Variables:
        ENVIRONMENT: production
        DD_API_KEY: <your Datadog API key>
        DD_SITE: datadoghq.com
        DD_LOGS_INJECTION: "true"
    Events:
      MyEvent:
        Type: Api
        Properties:
          Path: /email
          Method: post

