AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin/whatsapp
      Handler: main
      Runtime: go1.x
      Timeout: 30
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role"
      Environment:
        Variables:
          ENVIRONMENT: production
      Events:
        MyEvent:
          Type: Api
          Properties:
            Path: /whatsapp
            Method: post
